### ISSUE TITLE
Class 'Plaid' not found error

### ISSUE THREAD

**Issue by pratheeshchambeth** [TomorrowIdeas/plaid-sdk-php#10]
Hi,
 I installed the library using composer as per the readme but getting a class not found error. The code looks like this
<?php
 require 'vendor/autoload.php';
 $client = new Plaid("xxxxxmyid", "xxxxmysecret", "xxxxxpublickey");
 $client->setEnvironment("sandbox");
?>

error is:
Fatal error: Uncaught Error: Class 'Plaid' not found in /Users/pratheesh/tutorials/plaid/composer/test.php:3

Could you please point me in the right direction ?

-Pratheesh

**Comment by kgdiem** [comment]
Is this the first composer package you’ve added to the project? Is your
project set up for PSR4 imports?

**Comment by brentscheffler** [comment]
Did you add:

```php
include __DIR__ . "/vendor/autoload.php";
```

**Comment by brentscheffler** [comment]
I cannot seem to reproduce, nor do any of the unit tests fail.

```php
use TomorrowIdeas\Plaid\Plaid;

require __DIR__ . "/vendor/autoload.php";

$plaid = new Plaid(
    "client_id",
    "client_secret",
    "public_key"
);

$plaid->setEnvironment("sandbox");
$plaid->setVersion("2019-05-29");

$response = $plaid->getItem("itm_2134");
```

**Comment by eskimo** [comment]
The `use` is where I went wrong and same as the other guy probably. You should add that to the example in the readme since people that don't typically use composer wouldn't know this.
