### ISSUE TITLE
getAssetReportPdf should not have include_insights as a parameter

### ISSUE THREAD

**Issue by cshawshank** [TomorrowIdeas/plaid-sdk-php#11]
Getting a 400 Bad Request when calling the getAssetReportPdf() function.

After further inspection, removing the "include_insights" parameter from the Plaid.php class, resolves the error.

The "include_insights" parameter is not mentioned in the Plaid Docs. It should be removed from this function.

**Comment by brentscheffler** [comment]
Issue resolved in 0.7 release.

**Comment by jayomayan** [comment]
@cshawshank I'm having Bad Request on creating Asset Report.
Do you mind sharing how you did the createAssetReport .

Thanks
