### ISSUE TITLE
Payment initiation support

### ISSUE THREAD

**Issue by princerafid01** [TomorrowIdeas/plaid-sdk-php#14]
Hi, I am wondering how could I use payment initiation with your wonderful package?
Thank you.

**Comment by brentscheffler** [comment]
Plaid is not a payment processor. It is for syncing bank data.

**Comment by princerafid01** [comment]
But [here](https://plaid.com/docs/#payment-initiation) it said that i can accept payment with plaid.

**Comment by brentscheffler** [comment]
Ah, being in the US, I never saw this part of the documentation before as it's only available in the UK. Adding this as a feature request. Thanks!

**Comment by brentscheffler** [comment]
This has not been merged in yet, so issue should not be closed.

**Comment by brentscheffler** [comment]
Support for Payment Initiation now merged into 0.10 release.
