### ISSUE TITLE
Support for Link token creation

### ISSUE THREAD

**Issue by ChrisHawley** [TomorrowIdeas/plaid-sdk-php#17]
I propose that we add support for the `/link/token/create` endpoint similar to what is offered in the [official Node sdk](https://github.com/plaid/plaid-node/blob/master/lib/PlaidClient.js#L120).

Happy to take this one myself, but please feel free to leave feedback here.

Ref: https://plaid.com/docs/#create-link-token

**Comment by brentscheffler** [comment]
@ChrisHawley Thanks for stepping up. I actually started working on this last night after @elliotkoss reported it in issue #16 .

My proposed updates, causing the least amount of breaking change:

* Alter constructor signature to allow **$public_key** to be null with a default value of null.
* Add new **createLinkToken** method.

The only thing the public key *was* being used for were a couple Plaid endpoints that didn't need client credentials, so instead they required your public key. However, those endpoint look to have been updated as well to need client credentials, making the **$public_key** property completely unnecessary, except to maintain backwards compatibility.

Not sure why Plaid didn't release all these changes into a new API version - but here we are.

**Comment by ChrisHawley** [comment]
👍 Sounds like a good approach to me. Let me take a whack at it and we can go from there.

**Comment by brentscheffler** [comment]
I had some time over the weekend to  implement most of the above. Will be pushing to dev-master.

**Comment by ChrisHawley** [comment]
Ahh ok -- I did much of this as well, but https://github.com/TomorrowIdeas/plaid-sdk-php/commit/aa3e6edd2a746814ce3519f0311f238047510c5d looks stellar. 👍
