### ISSUE TITLE
Listing on Plaid API clients page

### ISSUE THREAD

**Issue by kgdiem** [TomorrowIdeas/plaid-sdk-php#2]
Getting this project listed on the [Plaid libraries page](https://plaid.com/docs/libraries) would be great for discoverability, getting continued community support. 

This is by far the most complete and up to date PHP client, very clean and readable code but it isn’t the top result on Google/Github. 

BTW — I understand that this repo was only created about 2 weeks ago. I just want to make sure the library remains supported by you, me, the community at large 🙃.

**Comment by brentscheffler** [comment]
We are now listed on the Plaid libraries page as a Community Library! Now I can finally close this issue. :-)
