### ISSUE TITLE
item_errors are reduced to a "Bad Request" error, instead of forwarding the item error from Plaid

### ISSUE THREAD

**Issue by vjotchere** [TomorrowIdeas/plaid-sdk-php#21]
When a request to a plaid endpoint fails due to an item error, typically from functions like 'getAccounts' and 'getTransactions', the PlaidRequestException outputs "Bad Request". It would be most useful for the exception handler to forward the error message sent from plaid using something like
`\json_decode($response->getBody()->getContents())`
so that that error message can be forwarded to the end users in instances where an update needs to happen through Link

**Comment by brentscheffler** [comment]
It should already do this.

When the exception is thrown, the entire Response object is passed into the exception and then parsed. The exception code should match the HTTP status code. The exception message should also be passed through from the Response as well, unless Plaid changed the shape of their error responses.

**Comment by brentscheffler** [comment]
```php

$plaidRequestException->getCode(); // Should match the HTTP response code Plaid returned
$plaidRequestException->getMessage(); // Should be the display message from Plaid
$plaidRequestException->getResponse(); // Should be the full JSON decoded object Plaid returned in response body

```

**Comment by vjotchere** [comment]
the getResponse() method was what I was looking for and missed, thank you
