### ISSUE TITLE
Automatically launch on the credentials pane during link update mode

### ISSUE THREAD

**Issue by brycematheson** [TomorrowIdeas/plaid-sdk-php#22]
On this page in the Plaid documentation, it talks about during Plaid Link Update mode, you can configure the application to automatically launch on the credentials page of the given institution:

https://support.plaid.com/hc/en-us/articles/360010529653-Updating-Items-via-Plaid-Link

![image](https://user-images.githubusercontent.com/7937222/91486617-c9054f80-e869-11ea-9999-e6091e7366cd.png)

Does this SDK support this capability?

**Comment by brentscheffler** [comment]
Yes it does! When calling the `createLinkToken` method, pass the in the `$access_token` of the Item that needs refreshing/updating.

**Comment by brycematheson** [comment]
Thank you very much! Appreciate the prompt response as well. This is exactly what I was looking for.
