### ISSUE TITLE
Newest Plaid version 2020-09-14 is not supported

### ISSUE THREAD

**Issue by DarkSide666** [TomorrowIdeas/plaid-sdk-php#24]
Newest Plaid version 2020-09-14 is not supported

**Comment by temuri416** [comment]
Hello,

Is there any timeline on 2020-09-14 support? 

Thanks!

**Comment by brentscheffler** [comment]
A pretty major refactor of the SDK will be made available that will have 2020-09-14 support. This work will be available in the next week or two and has some pretty major breaking changes. You can take a look in the 1.0-dev branch.

**Comment by DarkSide666** [comment]
Looks like that refactor will not be back-ward compatible with current release, right?

**Comment by FrankWiebe** [comment]
When will this be released? I'm looking to integrate this and want to wait for this release.

**Comment by brentscheffler** [comment]
1.0 was released! Sorry for the delay, but there were a lot of updates and enhancements needed for this release.
