### ISSUE TITLE
Payment Initiation createRecipient

### ISSUE THREAD

**Issue by blu-towers** [TomorrowIdeas/plaid-sdk-php#25]
You can use bacs account and sort code also not just iban, sometimes iban is not available.

https://plaid.com/docs/api/products/#payment_initiationrecipientcreate

**Comment by brentscheffler** [comment]
This was a new option added in the 2020-09-14 Plaid API release. There will be a forthcoming release that will add this functionality.

**Comment by brentscheffler** [comment]
1.0 release has added this functionality.
