### ISSUE TITLE
Missing options argument for 'accounts/get' in Accounts.php

### ISSUE THREAD

**Issue by dannyYassine** [TomorrowIdeas/plaid-sdk-php#33]
Hi all!

As per the [Plaid documentation for `accounts/get`](https://plaid.com/docs/api/accounts/#accountsget), there is an optional `options` object we can pass in order to filter by account_ids.

This is missing from the php client. My code snippet below adds the missing function argument in `Accounts.php`:

```php
/**
  * Get all Accounts.
  *
  * @param string $access_token
  * @param array $options
  * @return object
  */
public function list(string $access_token, array $options = []): object
{
        $params = [
	        "access_token" => $access_token,
	        "options" => (object) $options
        ];

        return $this->sendRequest(
	        "post",
	        "accounts/get",
	        $this->paramsWithClientCredentials($params)
        );
}
```	

I am currently integrating the Plaid API to our app, and this is needed to continue with our development.

Thank you for your time and thank you for this PHP client, it really helped us move forward with the Plaid integration.

Danny Y.

**Comment by brentscheffler** [comment]
This has been resolved in 1.0.4 release.
