### ISSUE TITLE
TomorrowIdeas \ Plaid \ PlaidRequestException (400) Bad Request

### ISSUE THREAD

**Issue by gigalabs18** [TomorrowIdeas/plaid-sdk-php#35]
I am using this package(0.14.0) wrapper in php framework (laravel) as below.
```
use TomorrowIdeas\Plaid\Plaid;

$plaid = new Plaid(
  			$clientId,
  			$secretKey,
  			'development'
  		);

    	$item = $plaid->createLinkToken('name of user', 'es', ['US'],'unique_user_id',["auth"]);
    	
    	return $this->sendSuccessResponse('role', $item, 'role stored successfully!');
```
it return me an error as TomorrowIdeas \ Plaid \ PlaidRequestException (400) Bad Request don't why although clientId, secret is correct.

**Comment by brentscheffler** [comment]
What Plaid API version are you using? Can you add a `try... catch` around the the `createLinkToken` call and send the contents of: `\dd($exception->getResponse())`?

For example:
```php
try {
    $item = $plaid->createLinkToken('name of user', 'es', ['US'],'unique_user_id',[]);
} catch ( PlaidRequestException $exception) {
   \dd($exception->getResponse());
}
```

**Comment by gigalabs18** [comment]
> What Plaid API version are you using? Can you add a `try... catch` around the the `createLinkToken` call and send the contents of: `\dd($exception->getResponse())`?
> 
> For example:
> 
> ```
> try {
>     $item = $plaid->createLinkToken('name of user', 'es', ['US'],'unique_user_id',[]);
> } catch ( PlaidRequestException $exception) {
>    \dd($exception->getResponse());
> }
> ```

i am using 0.14.0 version and it generate an error now 205 bad request

**Comment by brentscheffler** [comment]
Sounds like you are on PHP 7.2 and are locked into the 0.14 release. Can you send the contents of:

```php
try {
    $item = $plaid->createLinkToken('name of user', 'es', ['US'],'unique_user_id',[]);
} catch ( PlaidRequestException $exception) {
   \dd($exception->getResponse());
}
```
To know exactly what the issue is, I need to see the error being returned by Plaid.

**Comment by gigalabs18** [comment]
> Sounds like you are on PHP 7.2 and are locked into the 0.14 release. Can you send the contents of:
> 
> ```
> try {
>     $item = $plaid->createLinkToken('name of user', 'es', ['US'],'unique_user_id',[]);
> } catch ( PlaidRequestException $exception) {
>    \dd($exception->getResponse());
> }
> ```
> 
> To know exactly what the issue is, I need to see the error being returned by Plaid.

<?php

namespace App\Http\Controllers\API;

```
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Controllers\API\BaseController as BaseController;
use TomorrowIdeas\Plaid\Plaid;

class PlaidController extends BaseController
{
    public function auth() {
    	$clientId  = "***********************";
    	$secretKey = "**************************";
    	$env = "development";
    	$plaid = new Plaid(
  			$clientId,
  			$secretKey,
  			$env
  		);
      try {
        $item = $plaid->createLinkToken('hassan shafique', 'es', ['US'],'unique_user_id',["auth"]);
      } catch ( PlaidRequestException $exception) {
         
         return dd($exception->getResponse());
      }
    	return $this->sendSuccessResponse('item', $item, 'item created successfully!');
    }
}
```

**Comment by gigalabs18** [comment]
should i update php version ? please guide

**Comment by gigalabs18** [comment]
Now i update the php version 7.3 and package  version to latest.

`class PlaidController extends BaseController
{
    public function auth() {

    	$plaid = new Plaid(
          $clientId,
          $secretKey,
          $env
        );
      try {
        $token = $plaid->tokens->create('plaid api application', 'en', ["US"], '1');
      } catch ( PlaidRequestException $exception) {
         
        dd($exception->getResponse());
      }
    	return $this->sendSuccessResponse('token', $token, 'token get successfully!');

    }
}`

error is 
message: "Argument 4 passed to TomorrowIdeas\Plaid\Resources\Tokens::create() must be an instance of TomorrowIdeas\Plaid\Entities\User, instance of App\User given, called in PlaidController.php on line 26"

**Comment by brentscheffler** [comment]
The issue is you are referencing the current master documentation which is drastically different than the version you are on (version 0.14). Your constructor parameters are incorrect. For version 0.14, you need to either include your `public key` or set it to null in the constructor. For example:

```php
$plaid = new Plaid(
	$client_id,
	$client_secret,
	null,
	"development"
);
```

Or you can upgrade your PHP version to at least 7.3 and update the SDK to the 1.x version.

**Comment by gigalabs18** [comment]
Yes i upgrade php and package version now it is running perfectly.
