### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by eldan88** [TomorrowIdeas/plaid-sdk-php#38]
Hi, 

I am trying to get a list of transactions and it keeps saying bad request. Not sure what I am doing wrong here. Below is my code

```



        $start   = new DateTime("2021-05-01",new DateTimeZone("America/New_York"));
        $end     = new DateTime("2021-05-20",new DateTimeZone("America/New_York"));

        $transactions = $client->transactions->list($token,$start,$end);
```

**Comment by brentscheffler** [comment]
Can you paste the contents of the raw response from Plaid?

```php
try {
    $transactions = $client->transactions->list($token,$start,$end);
} catch (\Exception $e) {
    die(print_r($e->getResponse(),true));
}
```

**Comment by eldan88** [comment]
Thanks for the reply. 

INVALID_ACCESS_TOKEN [error_message] => provided token is the wrong type. expected "access", got "public" [error_type] => INVALID_INPUT 

This is what I am using to get a token
      $response   =   $client->sandbox->createPublicToken("ins_3",array("transactions"));



        $token  =  $response->public_token;

**Comment by brentscheffler** [comment]
I think your issue is stated in the response:

`provided token is the wrong type. expected "access", got "public"`

**Comment by eldan88** [comment]
I dont get it. That is the only token you provide on your library

**Comment by brentscheffler** [comment]
Each item will have its own access token, I believe you should be using that token. Again, I think reading the API documentation for Plaid and how their workflow and endpoints behave would clear up a lot of the confusion.

**Comment by brentscheffler** [comment]
Here's a direct link to their documentation on how public token to access token transactions need to happen:

https://plaid.com/docs/api/tokens/#token-exchange-flow

**Comment by eldan88** [comment]
I have tried doing what you mentioned and I am getting this message
PRODUCT_NOT_READY [error_message] => the requested product is not yet ready. please provide a webhook or try the request again later
