### ISSUE TITLE
Token Exchange

### ISSUE THREAD

**Issue by karlmonson** [TomorrowIdeas/plaid-sdk-php#39]
Does this package support exchanging the public_token for a permanent access_token? I can't seem to figure out how to accomplish it with this package, but it's required functionality it seems. Any advice?

**Comment by brentscheffler** [comment]
It does indeed:

```php
$access_token = $plaid->items->exchangeToken($public_token);
```

**Comment by karlmonson** [comment]
Thanks @brentscheffler!
