### ISSUE TITLE
Plaid Income Verification API Error: No case in PaneSelector for beta_upload

### ISSUE THREAD

**Issue by tausif-ahmed** [TomorrowIdeas/plaid-sdk-php#46]
Hello @all,

I am using Plaid IncomeVerification API: https://plaid.com/docs/api/products/#incomeverificationcreate

The Steps I'm following are:

Step-1: Calling API: **/income/verification/create** to get the **income_verification** and **request_id**.

Step-2: After getting the **income_verification_id** from step-1, calling API: **/link/token/create** to get the link_token.

Step-3: After getting the **link_token** from step-2. On the client-side, using the link_token to initialize the Link.

Step-4: It opens a Plaid popup but shows an error when I try to upload a paystub(see screenshot).

Anyone facing the same problem? Please let me know the solution

Thanks in advance

![paid-income-error](https://user-images.githubusercontent.com/35405147/138148024-aec9025e-8486-442b-abcc-09bc85d466c4.png)

**Comment by brentscheffler** [comment]
I believe this issue is for the React/JS SDK. Closing issue due to non-response.
