### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by izuuarch** [TomorrowIdeas/plaid-sdk-php#69]
TomorrowIdeas\Plaid\Resources\Tokens::create(): Argument #4 ($user) must be of type TomorrowIdeas\Plaid\Entities\User, string

I am having the error above, but it seems i inputed everything in order
Heres the code:
       $redirecturi = "http://127.0.0.1:8000/user/transactions";
        $plaid = new Plaid(
            "63a5f55a11292c0014529866",
            "c4e8c4647df1c7c734a0ad27cf9de4",
            "sandbox"
        );
        $token = $plaid->tokens->create(
            "transaction", 
            "en", 
            ["US"], 
            "12344",
            ["transaction"],
            $redirecturi
        );

**Comment by brentscheffler** [comment]
This is not a bug. You are passing in a string value into the create method for the `User`. The `User` should be an instance of `TomorrowIdeas\Plaid\Resources\Tokens`.
